### ISSUE TITLE
PhoneGap Build - cli-6.3.0 gives wrong icon for iPhone 6 plus settings screen

### ISSUE THREAD

**Issue by RichardLewin87** [phonegap/phonegap-cli#636]
When using cli 6.0.0 and above building an app results in the failure to override default icon with the dimension 87x87 created when building the app with the icon specified in the config.xml file. This results in a built app having the correct icon in the list of apps but not the correct icon when viewing the settings in the iPhone 6 plus settings, resulting in seeing the Cordova robot icon. I have noticed this is also an issue with the icon with dimension of 167x167.
 
It would appear this issue has been present since 6.0.0 going by the following posted on c.getsatisfaction.com about 6 months ago:
 
[https://c.getsatisfaction.com/nitobi/topics/cli-6-0-0-gives-wrong-icon-and-splash-on-ios?t opic-reply-list[settings][page]=2#topic-reply-list](url)
 
I have been using PhoneGap Build with cli 5.4.1 for a while now and as mentioned at the start, the issue does not appear. However, I need to upgrade to cli 6.0.0 and above due to needing to have access to some of the latest API's in Android.
 
So my main question now is is there a fix for this that I am not aware of or is this still an issue and if so is there a plan to fix it around the corner as it is? I can understand in the grand scheme of this this is not a huge bug, but the end result of the builds I do are for commercial customers and therefore I can't have the Cordova robot in the settings screen.

**Comment by surajpindoria** [comment]
Hi @RichardLewin87,

This is something I have noticed in the PG Developer App as well. It is most likely an issue Cordova but we will continue to investigate.

https://github.com/phonegap/phonegap-app-developer/issues/428

**Comment by surajpindoria** [comment]
This is actually not related to the dev app issue above. Tested using phonegap-app-star-track using both the CLI and Build. CLI correctly uses the icons but the ipa downloaded from Build does not.

@wildabeast Can you take a look at this?

**Comment by RichardLewin87** [comment]
@surajpindoria, thank you for looking into the issue on your side and getting a more detailed knowledge of where the issue lies away from CLI.

**Comment by matthewgertner** [comment]
+1 big issue for us as well since upgrading to 6.x.x.

**Comment by JefferE** [comment]
+10 issue for us. The push notification icon is also the default phonegap icon.

We can not revert/continue to use 5.4 because the in-app purchase plugin requires 6.x

**Comment by matthewgertner** [comment]
Any news on this? Would it be better to file in the PGB repo issues?

**Comment by FlossyWeb** [comment]
+1 notification, settings and multitask view icons are all set to phonegap's default icon, issue is really cli-6.x related using pgb.

**Comment by goya** [comment]
a fix has been pushed to production

**Comment by gazzaf** [comment]
Hi. I've just rebuilt an app with PGB / cli-6.3.0 and the iOS push notification icon is still showing as the default PGB icon. If I rebuild using cli-5.4.1 the notification shows my correct custom icon. This bug still appears to be present, unless I'm supposed to specify cli-6.3.1 or something? Any ideas please @goya ? Thanks.

**Comment by goya** [comment]
please start an issue on https://forums.adobe.com/community/phonegap/build so we can troubleshoot, please include an app id of an app that can replicate this issue.  if you have already started a discussion on the adobe forums please post it here.

**Comment by gazzaf** [comment]
In the Adobe forums I commented about this on an existing thread. See last comment: https://forums.adobe.com/message/8918543
My app's current build using 5.4.1 so I can carry on developing. Do you want me to create a new app using 6.3.0 so you can replicate the issue?

**Comment by gazzaf** [comment]
@goya There is still no resolution for this bug. :-( I posted a new thread in the Adobe forum as you suggested 17 days ago but no one has replied.
https://forums.adobe.com/thread/2199023

**Comment by FlossyWeb** [comment]
@gazzaf You should add two more icons sized 58px and 87px square for multitask and notifications to show your app icon... Like this:
`<icon src="icons/ios/icon-58.png" platform="ios" width="58" height="58" />`
and
`<icon src="icons/ios/icon-87.png" platform="ios" width="87" height="87" />`
You can also take a look at this from Apple guidelines: https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon/
I don't know why we have to do this since cli-6.x but it should do the trick !

**Comment by gazzaf** [comment]
@FlossyWeb - Thank you! That solved the problem. :-) :-) :-)
In an ideal world wouldn't it be easier and smarter if iOS automatically takes a high res icon and resizes it on the fly for all  purposes? I've  got 8 different sizes of the same icon for iOS. As for splashscreens, half of my app's size is consumed by various sizes of splashscreens! In PGB 6.3.0 it's no longer smart enough to pick a screen automatically (it's now showing the PGB logo) so I have to create another screen - another 300Kb.
Lastly an observation with 6.3.0 notification icons. The transparent background I use is showing up as white. I'm sure it used to be black which looked invisible against the notification area's background.

**Comment by amitdangwal** [comment]
I am still facing the same issue. Default cordova icons appearing instead of icon defined in config.xml. It is happening on iphone and ipad both. I have created a separate ticket for this as it is marked as close here. If anyone has any input to share then please do guide. icons appear if I choose 5.3 cli but disappear(default visible) in 6.3
https://github.com/phonegap/phonegap-cli/issues/660

**Comment by FlossyWeb** [comment]
@amitdangwal have you tried what I commented previously ? 
"You should add two more icons sized 58px and 87px square for multitask and notifications to show your app icon... Like this:
<icon src="icons/ios/icon-58.png" platform="ios" width="58" height="58" />
and
<icon src="icons/ios/icon-87.png" platform="ios" width="87" height="87" />
"

**Comment by amitdangwal** [comment]
@FlossyWeb,  Yes I did add that after reading the comment here but it did not worked. Now I am trying to troubleshoot it by creating a new example phonegap app through cli and comparing the config.xml with my app and image files

**Comment by FlossyWeb** [comment]
@amitdangwal Sorry it didn't work for you, as a matter of fact this solved the issue for others and me that are building on PGB, I don't know if my code for icons works properly for cli builds as the config.xml could be slightly different... Good luck man

**Comment by amitdangwal** [comment]
@FlossyWeb, issue is resolved for me. Concern was that the image resolution was not same as mentioned in config and that is why it was not picking the given image in ios. I corrected the images and added with correct resolution. It was not the issue in CLI 5.2 but 6.3 seem to be more strict. Thanks for your input

**Comment by surajpindoria** [comment]
Glad to hear you got this working @amitdangwal!

**Comment by wang666** [comment]
After adding the 87x87 image file and updating the config.xml, custom icon is displayed properly in Settings and multi task view in iOS.
Took me a while to find this answer, thanks!!

**Comment by ChastinaLi** [comment]
@amitdangwal You saved my day!!! 👍

**Comment by canado** [comment]
Hello everyone, 
I think the  problem is back, at least for me. The cli I am using is cli-6.5.0 (4.3.1 / 6.1.2 / 4.4.3)
My app keeps being rejected by apple app store team.

After some investigation I discovered that no matter how much icon I add in the config.xml,  the IPA file contains only the default cordova ones.

I did a test with a previous IPA which I compiled last october 2016, and with a compile I did today
Here is the result after extracting all assets from both IPAs

![ipa-icons](https://user-images.githubusercontent.com/845879/27141584-96c65036-50f6-11e7-9dca-7c612f014eab.jpg)

As you can see my previous build contains my icons, ( and other default cordova as well )
but the  new build, contains only the default ones.

My questions is, how can I fix this ? Is the  problem from my side, or is the problem from the PGB compiling process ?

thanks

**Comment by al404** [comment]
I can't fix that too, since is my first phone gap app i'm not sure about 2 things 

Can I give the icon the name i like or do i need to rename based on a naming convention ?
Do I need to remove and add again iOS platform?
Any way to manually check if icon are updated under iOS?

`<platform name="ios">
	<icon src="res/icons/ios/icon-20.png" width="20" height="20" />
	<icon src="res/icons/ios/icon-20@2x.png" width="40" height="40" />
	<icon src="res/icons/ios/icon-20@3x.png" width="60" height="60" />
	    
        <icon src="res/icons/ios/icon-29.png" width="29" height="29" />
        <icon src="res/icons/ios/icon-29@2x.png" width="58" height="58" /> 
        <icon src="res/icons/ios/icon-29@3x.png" width="87" height="87" />
        
        <icon src="res/icons/ios/icon-40.png" width="40" height="40" />
        <icon src="res/icons/ios/icon-40@2x.png" width="80" height="80" />
        <icon src="res/icons/ios/icon-40@3x.png" width="120" height="120" />
        
        <icon src="res/icons/ios/icon-50.png" width="50" height="50" />
        <icon src="res/icons/ios/icon-50@2x.png" width="100" height="100" />
        
        <icon src="res/icons/ios/icon-57.png" width="57" height="57" />
        <icon src="res/icons/ios/icon-57@2x.png" width="114" height="114" />
        
        <icon src="res/icons/ios/icon-60.png" width="60" height="60" />
        <icon src="res/icons/ios/icon-60@2x.png" width="120" height="120" />
        <icon src="res/icons/ios/icon-60@3x.png" width="180" height="180" />
        
        <icon src="res/icons/ios/icon-72.png" width="72" height="72" />
        <icon src="res/icons/ios/icon-72@2x.png" width="144" height="144" />
        
        <icon src="res/icons/ios/icon-76.png" width="76" height="76" />
        <icon src="res/icons/ios/icon-76@2x.png" width="152" height="152" />
        
        <icon src="res/icons/ios/icon-83.5@2x.png" width="167" height="167" />       
    </platform>`

**Comment by amitdangwal** [comment]
More then file name what matters is
1. actual resolution of image  (open the image in editor and verify the actual resolution)
2. width and height tag given in config.xml for ios  ex. width="180" height="180"

**Comment by al404** [comment]
I did check and the image dimension are correct but in iOS multitasking on iPhone i see Cordova robot icon, on iPad i see the correct app icon

**Comment by amitdangwal** [comment]
You are probably missing the iphone based resolution defination(and or files) in config.xml. I had the exact same issue which got resolved for me when I corrected the image resolution for iphone as mentioned above(added below). See if that helps 

"@gazzaf You should add two more icons sized 58px and 87px square for multitask and notifications to show your app icon... Like this:
<icon src="icons/ios/icon-58.png" platform="ios" width="58" height="58" />
and
<icon src="icons/ios/icon-87.png" platform="ios" width="87" height="87" />
You can also take a look at this from Apple guidelines: https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon/
I don't know why we have to do this since cli-6.x but it should do the trick !"

**Comment by al404** [comment]
I did check and add all of them

<icon src="res/icons/ios/icon-29.png" width="29" height="29" />
<icon src="res/icons/ios/icon-29@2x.png" width="58" height="58" /> 
<icon src="res/icons/ios/icon-29@3x.png" width="87" height="87" />

that is why I was asking if the file name is important and if i need to remove and add again iOS platform

`<platform name="ios">
	    <icon src="res/icons/ios/icon-20.png" width="20" height="20" />
	    <icon src="res/icons/ios/icon-20@2x.png" width="40" height="40" />
	    <icon src="res/icons/ios/icon-20@3x.png" width="60" height="60" />
	    
        <icon src="res/icons/ios/icon-29.png" width="29" height="29" />
        <icon src="res/icons/ios/icon-29@2x.png" width="58" height="58" /> 
        <icon src="res/icons/ios/icon-29@3x.png" width="87" height="87" />
        
        <icon src="res/icons/ios/icon-40.png" width="40" height="40" />
        <icon src="res/icons/ios/icon-40@2x.png" width="80" height="80" />
        <icon src="res/icons/ios/icon-40@3x.png" width="120" height="120" />
        
        <icon src="res/icons/ios/icon-50.png" width="50" height="50" />
        <icon src="res/icons/ios/icon-50@2x.png" width="100" height="100" />
        
        <icon src="res/icons/ios/icon-57.png" width="57" height="57" />
        <icon src="res/icons/ios/icon-57@2x.png" width="114" height="114" />
        
        <icon src="res/icons/ios/icon-60.png" width="60" height="60" />
        <icon src="res/icons/ios/icon-60@2x.png" width="120" height="120" />
        <icon src="res/icons/ios/icon-60@3x.png" width="180" height="180" />
        
        <icon src="res/icons/ios/icon-72.png" width="72" height="72" />
        <icon src="res/icons/ios/icon-72@2x.png" width="144" height="144" />
        
        <icon src="res/icons/ios/icon-76.png" width="76" height="76" />
        <icon src="res/icons/ios/icon-76@2x.png" width="152" height="152" />
        
        <icon src="res/icons/ios/icon-83.5@2x.png" width="167" height="167" />        
        
    </platform>`

**Comment by amitdangwal** [comment]
I am using custom names for icons and splash. It is working for me with it. for ex.

  <icon src="resources/icons/ios/logo-57x57.png" platform="ios" height="57" width="57" />
  <icon src="resources/icons/ios/logo-72x72.png" platform="ios" height="72" width="72" />
  <icon src="resources/icons/ios/logo-76x76.png" platform="ios" height="76" width="76" />
  <icon src="resources/icons/ios/logo-114x114.png" platform="ios" height="114" width="114" />
  <icon src="resources/icons/ios/logo-120x120.png" platform="ios" height="120" width="120" />
  <icon src="resources/icons/ios/logo-144x144.png" platform="ios" height="144" width="144" />
  <icon src="resources/icons/ios/logo-152x152.png" platform="ios" height="152" width="152" />
